### ISSUE TITLE
odkmeta error: invalid stub varname 

### ISSUE THREAD

**Issue by monicavargon123** [matthew-white/odkmeta#41]
Hi,
I am Mónica Vargas and I work in a non-profit-organization in Mexico. We have been using the ODK server to collect our surveys and the "odkmeta" stata program to clean them. Unfortunately, we haven't been able to run the import do file since the error "invalid stub cdp" (cdp is my variable) comes up.

We have 3 variables starting with cdp:
cdp cdp2 and cdp3 are required and "select_multiple" type variables which have a constraint (not(selected(.,'0') and count-selected(.)>1)). Each cdp* variable has about 5 questions which are relevant depending on the answer of cdp*.

We would like to solve this problem as soon as possible but we don't know how.
Your inputs on the matter would be truly appreciated.
Thanks a lot

**Comment by matthew-white** [comment]
Mónica notes on the ODK forum that she resolved the issue:

https://forum.opendatakit.org/t/odkmeta-error-in-stata-invalid-stub-varname/6947
