### ISSUE TITLE
odkmeta - question about using short names as variable name

### ISSUE THREAD

**Issue by HimalAllen** [matthew-white/odkmeta#43]
When creating the .do file using odkmeta to import a .csv from ODK , what are possible ways of having the .do file use the ODK_name (short name) as the variable name in STATA instead of the long name (which includes all group and nested group names)? The rest of odkmeta’s tasks work perfectly, just need the short name as the variable name in STATA instead of the long name (and to have that documented in the .do file if possible).

Thank you!

**Comment by matthew-white** [comment]
I just replied [on the ODK Forum](https://forum.opendatakit.org/t/odkmeta-using-short-name-of-variables/10167). Let me know if you have any questions there!
