### ISSUE TITLE
GPS coordinates commas turned into variables

### ISSUE THREAD

**Issue by danieljeannetot** [matthew-white/odkmeta#44]
Hi,

First thanks for the amazing work, ODKMeta is a great tool.
I am dealing with large many large data set and including GPS coordinates within.
Most of the time, the GPS coordinates include commas "," (at least in french)

E.g.: 2 different variable (lat/long) with originally two data points
_coordonnees_gps_latitude | _coordonnees_gps_longitude
-4,41657xxx | 15,379xxx _modified for example_

Will results in 4 data point after the do-file processing.
4 
41657xxx
15
379xxx

Given the way ODKmeta works, it automatically interprets the "," in the coordinates, as a different variable. 
Therefore from there, all the data is shifted by 2 columns (lat/long commas) to the right when executing the do-file made with ODKmeta.

Obviously the fix is to change the gps coordinates commas to dots. However if done in excel you may run into some difficulties where excel forces on you the comma or instead put dots for thousands (so every 3 numbers)

I don't know if anything can be done more systematically to avoid that, I simply wanted to raise the issue in case someone else runs into it.

Cheers

**Comment by matthew-white** [comment]
Interesting issue! Just to confirm, the field in question is `geopoint`, right?

.csv files typically require that a value containing a comma be enclosed in quotes. Otherwise, like you said, the comma will be interpreted as the field separator, not as part of the value, and the part of the value after the comma will go in the next column. There are two ways to address this sort of issue: (1) like you said, replace the commas with another character, or (2) without changing the value, enclose it in double quotes so that the importing software knows where the value begins and ends.

How did you export the .csv file? Using ODK Briefcase or through the server (ODK Aggregate, Ona, KoBo, etc.)? One option is for you to manually edit the data yourself in a text editor like Sublime Text or Notepad++. (Unlike Excel, those won't change the data except in the ways you specify.) However, it'd be even better if we could confirm whether the issue lies with the export tool and if so, see if a change could be made there.

**Comment by danieljeannetot** [comment]
Thanks for the reactivity Matthew.

The field in question is indeed `geopoint` , it's been exported in .csv through ONA.
I'll try the double quote as a solution on a small dataset.
Manually altering the data through notepad (basic) did help, however due to the size and the number of forms it will be wiser to try to find or script a solution on my side.
Let me know if I can help in any sort of way.

Related but slightly different: this comma problem also create an issue with another variable. It's a text input where surveyor can comment on the result of the survey or sometimes have to fill-in an "other" answer.
There, the surveyor may enter an answer sort of "blabla, blabla, blabla," just because it's a written answer or a sort of a listing. 
I realised that when I tried to apply the do-file to such dataset, stata(or the do-file, I am not sure) would also confuse the comma in the sentence (french sentence, lots of commas) as a field separator, and therefore, the sentence get splits into different columns "blabla"; "blabla";"blabla", creating columns and therefore shifting the answers for one respondent by several columns to the right. 

Since the commas have been troublesome, I dug a bit the comma handling. In the french/dutch version of excel, the delimiter or separator is usually a semicolon rather than a comma. (needs to be changed in the regional/language setting of Windows)
However, ODKMeta cannot handle the semicolon from what I encountered (might be wrong here).
Therefore I batched "find/replace" the semicolon in comma through notepad, and then exported the csv to stata to try to apply the do-file. 
I am wondering if that may have caused the issue for the geopoint and for the other variable, since the comma are also used in the answers.

I am not sure i am very clear on that second issue, and the issue might be broader than ODKMeta all together.

Thanks for you help!

EDIT: after checking out a bit more the handling of comma: I am using excel to split the ODK form (survey/choices) into CSV. This is where it goes from being comma to semicolon, and where I need to then change it back to comma. For that reason I am forced to batch find/replace semicolon to comma because otherwise ODKMeta provides an error
`column header type not found` 
`invalid type() suboption`
`invalid survey () option`
`r(111);`
The dataset being exported directly from ONA, it is using comma (no change needed)
I am leaning toward the fact that the batch find/replace of semicolon/comma is mixing up everything at a certain and that's why the handling of the comma get inconsistent. However that is just a supposition.

**Comment by matthew-white** [comment]
I tried downloading data from Ona for a form with a `geopoint` and a `text` field, and like you, I found that in this raw data, the latitude and longitude columns used a period, not a comma. I also found that `text` values that contained a comma were enclosed in quotes. Is it possible that you've been opening the .csv file in Excel and saving it before importing it to Stata? As you've seen, even if you don't edit a file in Excel, just the act of opening and saving it in Excel can change it in important ways. When importing to Stata, I recommend using the most raw form of the data, not data that has been opened and saved in Excel.

Note that `odkmeta` only works for data that is compatible with the ODK Briefcase format. I believe that Ona downloads use a different format, but you should be able to use ODK Briefcase together with Ona: see [here](https://help.ona.io/knowledge-base/how-do-i-use-odk-briefcase/).

Like you said, you'll still need to use Excel to split the form into survey and choices .csv files. `odkmeta` only supports comma-separated .csv files, not semicolon-separated. I recommend temporarily changing your regional settings when exporting those sheets or investigating whether there are export options in Excel to accomplish the same thing.

Hope that helps!

**Comment by danieljeannetot** [comment]
Hi Matthew,

In the end, the best and only way I found to overcome that issue is, simply, to do everything through Stata, that is importing the XLS and with the right sheet exporting it as csv afterward (so first survey, then choices) and then running ODKMeta. 
Works like a charm, that way excel does not screw up everything.

Thanks a lot.

**Comment by matthew-white** [comment]
Sounds good, I'm glad that worked!
