### ISSUE TITLE
Labelling with repeat and flaps 

### ISSUE THREAD

**Issue by danieljeannetot** [matthew-white/odkmeta#45]
Hi Matthew/ODKMeta dev team,

i am encountering a labelling issue when running ODKMeta on a dataset with different flaps (repeat).
For the sake of context, the questionnaire was based (when on paper) on flaps and allowed to switch between flaps depending on the questions and number of respondents (number of women in bearing age in household, for example).

I am only using ODK, and the data is being pulled from ONA (seeing what was said for SurveyCTO, etc.) 
The XLSForm is split directly in Stata
The data must be exported as a xls and be split through stata, as ODK will record the flaps as different sheets in ONA.

When running the ODKMeta-produced .do file for relabelling, I encounter this:

`variable KEY not found`
`variable PARENT_KEY not found`
`variable PARENT_KEY not found`
`variable PARENT_KEY not found`
`invalid syntax`
`invalid file specification`
`invalid syntax`
`invalid file specification`

Stata indicates it cannot find the KEY and Parent_key variable, but there is no such variable to be found anywhere when using flaps in ODK. 
It seems that ODKMeta is expecting to find such a variable.
Regarding file specification, I understand a .csv is needed from the flaps, but is a .dta also needed (or is it just a back-up if the .csv of the flap is not found)
I have that issue on two different datasets, both using flaps.

Would you have any idea? I am happy to provide more details.
Thanks for your help.
cheers,

**Comment by matthew-white** [comment]
Hi @cyannuremagik! We're actually trying to limit the GitHub issues tracker to verified bugs and feature requests. For support requests like this, I recommend posing your question on the ODK Forum. The question will get more visibility that way, and the answer will be easier to find for posterity. My username on the Forum is Matthew_White — feel free to mention me when you create the topic on the Forum.
